src/publishes/routes/web.php
<?php
Auth::routes();
Route::get('logout', function () {
    Auth::logout();
    return redirect('/');
});

Route::get('nao-autorizado', function () {
    return view('erros.nao_autorizado');
})->name('nao_autorizado');

Route::post('fill', 'SelectController@fill')->name('fill');
Route::post('getedit', 'SelectController@getEdit')->name('getEdit');

Route::group(['middleware' => ['auth', 'has-permission']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'usuario', 'as' => 'usuario.'], function () {
        Route::get('cadastro', function () {
            return view('usuario.cadastro');
        })->name('cadastro');

        Route::get('alterar_imagem/{id}', 'UsuarioController@alterarImagem')->name('alterar_imagem');
        Route::post('alterar_imagem/{id}', 'UsuarioController@salvarImagem')->name('imagem_post');
        Route::get('alterar_senha/{id}', 'UsuarioController@alterarSenha')->name('alterar_senha');
        Route::delete('delete_img/{id}', 'UsuarioController@deleteImg')->name('delete_img');
        Route::post('alterar_senha/{id}', 'UsuarioController@salvarSenha')->name('salvar_senha');
        Route::post('alterar_cadastro/{id}', 'UsuarioController@alterarCadastro')->name('alterar_cadastro');

    });

    // Tipo de usuário
    Route::group(['prefix' => 'tipo_usuario', 'as' => 'tipo_usuario.'], function () {
        Route::post('carregar-permissoes', 'TipoUsuarioController@carregarPermissoes')->name('carregar_permissoes');
        Route::get('gerenciar-permissoes', 'TipoUsuarioController@gerenciarPermissoes')->name('gerenciar_permissoes');
        Route::post('gerenciar-permissoes', 'TipoUsuarioController@salvarPermissoes')->name('gerenciar_permissoes.post');
    });

    Route::resource('sis_usuario', 'SisUsuarioController');
    Route::group(['prefix' => 'sis_usuario', 'as' => 'sis_usuario.'], function () {
        Route::get('getedit/{id}', 'SisUsuarioController@getedit')->name('getedit');
        Route::post('fill', 'SisUsuarioController@fill')->name('fill');
    });

    Route::resource('aux_tipo_usuario', 'AuxTipoUsuarioController');
    Route::group(['prefix' => 'aux_tipo_usuario', 'as' => 'aux_tipo_usuario.'], function () {
        Route::get('getedit/{id}', 'AuxTipoUsuarioController@getedit')->name('getedit');
        Route::post('fill', 'AuxTipoUsuarioController@fill')->name('fill');
    });
    Route::resource('rota', 'RotaController');
    Route::group(['prefix' => 'rota', 'as' => 'rota.'], function () {
        Route::get('getedit/{id}', 'RotaController@getedit')->name('getedit');
        Route::post('fill', 'RotaController@fill')->name('fill');
    });

    Route::resource('tipo_rota', 'TipoRotaController');
    Route::group(['prefix' => 'tipo_rota', 'as' => 'tipo_rota.'], function () {
        Route::get('getedit/{id}', 'TipoRotaController@getedit')->name('getedit');
        Route::post('fill', 'TipoRotaController@fill')->name('fill');
    });
    //[rota]
});

src/publishes/app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\Http\Requests\SalvarCadastroRequest;
use App\Http\Requests\SalvarImagemRequest;
use App\Http\Requests\SalvarSenhaRequest;
use App\Models\SisUsuario;

class UsuarioController extends Controller
{

    private $listagem;

    public function alterarImagem($id)
    {
        if (auth()->user()->tipo_usuario_id == 3) {
            $id = auth()->user()->id;
        }
        $usuario = SisUsuario::find($id);
        return view('usuario.imagem', compact('usuario'));
    }

    public function salvarImagem($id, SalvarImagemRequest $request)
    {
        if (auth()->user()->tipo_usuario_id == 3) {
            $id = auth()->user()->id;
        }
        $file = $request->photo->store('photo');
        $input = $request->all();
        $input['photo'] = $file;
        $usuario = SisUsuario::find($id);
        $user = Auth::user();
        $user->update($input);
        $usuario->photo = $file;
        $atualizado = $usuario->save();
        if ($atualizado) {
            $res = ['res' => 1, 'imagem' => $usuario->photo];
            return response()->json($res);
        } else {
            return response()->json(['res' => 'erro']);
        }

        return redirect()->route('usuario.index');
    }

    public function deleteImg($id)
    {
        $res = ['res' => 1];
        return response()->json($res);
    }

    public function alterarSenha($id)
    {
        if (auth()->user()->tipo_usuario_id == 3) {
            $id = auth()->user()->id;
        }
        $usuario = SisUsuario::find($id);
        return view('usuario.senha', compact('usuario'));
    }

    public function salvarSenha($id, SalvarSenhaRequest $request)
    {
        if (auth()->user()->tipo_usuario_id == 3) {
            $id = auth()->user()->id;
        }
        $usuario = SisUsuario::find($id);
        $atualizado = $usuario->update($request->all());
        if ($atualizado) {
            $res = ['res' => 1];
            return response()->json($res);
        } else {
            return response()->json(['res' => 'erro']);
        }

    }

    public function alterarCadastro($id, SalvarCadastroRequest $request)
    {
        $atualizado = SisUsuario::find($id)->update($request->all());
        if ($atualizado) {
            flash("Os dados do registro foram alterados com sucesso.", 'success');
        }
        return redirect()->route('usuario.cadastro');
    }


}

src/publishes/resources/views/usuario/cadastro.blade.php
@extends('layouts.template')

@section('conteudo')
    <div class="this-place">
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{route('home')}}">Home</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span>Usuário</span>
                </li>
            </ul>
            <div class="page-toolbar">
                <div class="btn-group pull-right">
                    <button type="button" class="btn green btn-sm btn-outline dropdown-toggle" data-toggle="dropdown"
                            aria-expanded="false"> Ações
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu">
                        <li>
                            <a href="{{route('usuario.alterar_imagem',auth()->user()->id)}}" data-toggle="modal"
                               data-target="#modal">
                                <i class="fa fa-photo"></i> Alterar Imagem</a>
                        </li>
                        <li>
                            <a href="{{route('usuario.alterar_senha',auth()->user()->id)}}" data-toggle="modal"
                               data-target="#modal">
                                <i class="icon-shield"></i> Alterar Senha</a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <h1 class="page-title"> Cadastro
            <small></small>
        </h1>

        <div class="row">
            <div class="col-md-12">
                <div class="profile-sidebar">
                    <div class="portlet light profile-sidebar-portlet ">
                        <div class="profile-userpic">
                            <img src="{{!empty(auth()->user()->photo)? asset('storage/'.auth()->user()->photo) : asset('img/profile_user.jpg')}}"
                                 class="img-responsive" alt="" id="user-image"></div>
                        <div class="profile-usertitle">
                            <div class="profile-usertitle-name"> {{ auth()->user()->primeiroNome }} </div>
                            <div class="profile-usertitle-job"> {{ auth()->user()->tipoUsuario->descricao }} </div>
                        </div>
                        <div class="profile-userbuttons">
                            <a href="{{route('usuario.alterar_imagem',auth()->user()->id)}}"
                               class="btn btn-circle green btn-sm" data-toggle="modal" data-target="#modal">
                                Alterar Imagem</a>
                            <a href="{{route('usuario.alterar_senha',auth()->user()->id)}}"
                               class="btn btn-circle red btn-sm" data-toggle="modal" data-target="#modal">
                                Alterar Senha</a>
                        </div>
                        <div class="profile-usermenu">
                            <ul class="nav">
                                <li>
                                    <a href="{{route('home')}}">
                                        <i class="icon-home"></i> Home </a>
                                </li>

                                <li>
                                    <a href="page_user_profile_1_help.html">
                                        <i class="icon-info"></i> Ajuda </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="portlet light ">

                        <div>
                            <h4 class="profile-desc-title"> {{ auth()->user()->nome }}</h4>
                            <div class="margin-top-20 profile-desc-link">
                                <i class="fa fa-globe"></i>
                                <a href="#"> {{ auth()->user()->email }}</a>
                            </div>

                        </div>
                    </div>
                    <!-- END PORTLET MAIN -->
                </div>
                <div class="profile-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="portlet light ">
                                <div class="portlet-title tabbable-line">
                                    <div class="caption caption-md">
                                        <i class="icon-globe theme-font hide"></i>
                                        <span class="caption-subject font-blue-madison bold uppercase">Dados da conta</span>
                                    </div>
                                    <ul class="nav nav-tabs">
                                        <li class="active">
                                            <a href="#tab_1_1" data-toggle="tab">Dados Principais</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="portlet-body">
                                    <form role="form" method="post" class="validate"
                                          action="{{route('usuario.alterar_cadastro',auth()->user()->id)}}">
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="tab_1_1">
                                                <div class="form-group">
                                                    <label class="control-label" for="nome">Nome</label>
                                                    <input type="text" name="nome" id="nome" class="form-control"
                                                           value="{{ auth()->user()->nome }}" placeholder="Nome">
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="email">Email</label>
                                                    <input type="email" name="email" id="email" class="form-control"
                                                           value="{{ auth()->user()->email }}" placeholder="email">
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="telefone">Telefone</label>
                                                    <input type="text" name="telefone" id="telefone" class="form-control"
                                                           value="{{ auth()->user()->telefone }}" placeholder="Telefone" mask="phone">
                                                </div>

                                            </div>

                                        </div>
                                        <div class="margiv-top-10">
                                            <input type="submit" class="btn green" value="Salvar"/>
                                            <a href="{{route('home')}}" class="btn default"> Cancel </a>
                                        </div>
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/publishes/resources/views/usuario/imagem.blade.php
<div class="this-place">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="{{route('usuario.cadastro')}}">Usuário</a></li>
            <i class="fa fa-circle"></i>
            <li><span>Alterar Imagem</span></li>
        </ul>
    </div>
    <div class="clearfix"></div>
    <h1 class="page-title">Usuário</h1>
    <div class="clearfix"></div>
    <div class="row area">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-body ">
                    <form class="validate" method="post" role="form"
                          action="{{ route('usuario.imagem_post',$usuario->id) }}"
                          enctype="multipart/form-data" id="form-image">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="files">Imagem</label>
                                <input id="photo" type="file" name="photo" class="input-file-edit"
                                       link-img="{{!empty($usuario->photo)? asset('storage/'.auth()->user()->photo) : ''}}"
                                       descricao-img="{{$usuario->nome}}"
                                       controller-img="usuario" img-id="{{$usuario->id}}"
                                       data-overwrite-initial="false">
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-12">
                            <div class="progress" style="display: none;">
                                <div class="progress-bar progress-bar-striped active" role="progressbar"
                                     aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                    <span class="percent">0% Complete</span>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="text-right">
                            <a href="{{ route('usuario.cadastro') }}" class="btn btn-default" data-dismiss="modal" listen="f">Cancelar</a>
                            <input type="submit" class="btn btn-primary" value="Salvar"
                                   onclick="return change_photo('form-image')">
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/publishes/resources/views/usuario/senha.blade.php
@extends('layouts.modal')
@section('conteudo')
<div class="this-place">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="{{route('sis_usuario.index')}}">Usuário</a></li>
            <i class="fa fa-circle"></i>
            <li><span>Alterar Senha</span></li>
        </ul>
    </div>
    <div class="clearfix"></div>
    <h1 class="page-title">Usuário</h1>
    <div class="clearfix"></div>
    <div class="row area">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-body ">
                    <form class="" method="post" role="form" action="{{ route('usuario.salvar_senha',$usuario->id) }}"  id="form-senha">

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label" for="password">Senha</label>
                                <input type="password" name="password" id="password" class="form-control" placeholder="Senha" is="firstPass">
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label" for="password_confirm">Confirmação</label>
                                <input type="password" name="password_confirmation" id="password-confirm" class="form-control" placeholder="Senha" is="secondPass">
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <div class="text-right">
                            <a href="{{ route('sis_usuario.index') }}" class="btn btn-default" data-dismiss="modal" listen="f">Cancelar</a>
                            <input type="submit" class="btn btn-primary" value="Salvar"
                                   onclick="return change_senha('form-senha')">
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection